version: "3" 
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: bitnami/phpmyadmin
    restart: always
    ports:
      - '4013:8080'
    environment:
      DATABASE_HOST: db:3306
      DATABASE_USER: root
      DATABASE_PASSWORD: password

  wordpress:
    depends_on:
      - db
    build:
      context: .docker
      dockerfile: wordpress.Dockerfile
    image: wordpress
    restart: always
    volumes:
      - ./src/:/var/www/html
    ports:
      - "3013:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  mysql: